import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/layout'
import Link from 'next/link'
import { Button, Container, Divider, Grid, Stack, Toolbar, Typography, useMediaQuery, useTheme } from '@mui/material'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <>
      <Head>
        <title>NetCrafty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/title-logo.png" />
      </Head>

      <div className="slider-area slider-style-8 header-height">
        <div className="single-slide">
          <Container maxWidth="md">
            <div className="row align-items-center">
              <div className="col-lg-12">
                <Stack spacing={4}
                  textAlign={"center"}
                  alignItems={"center"}
                  justifyContent={"center"}
                >
                  <Link href="/">
                    <Image src="/netc2.png"
                      alt='NetCrafty'
                      width={isMobile ? 250 : 300}
                      height={isMobile ? 83 : 100}
                      style={{
                        display: "flex",
                        marginLeft: "auto",
                        marginRight: "auto"
                      }}
                      priority
                    />
                  </Link>
                  <h5>Ready To Scale Your Business?</h5>
                  <h1 className='fw-bold'>We&#39;ll Manage Your Advertising Campaigns For FREE Until You Get Results!</h1>
                  <Button size='large' className="btn-default">
                    <h3 style={{ marginBottom: '0rem' }}>Sign Up</h3>
                  </Button>
                </Stack>
              </div>
            </div>
          </Container>
        </div>
      </div >

      <Toolbar />
      {/* <Divider sx={{ borderColor: '#F8AC23', borderWidth: '2.5px' }} /> */}

      <Container>
        <Stack spacing={4} alignItems={"center"} justifyContent={"center"}>
          <Typography variant='h3' className='text-center text-golden fw-bold'>
            How does it work?
          </Typography>
          <Typography variant='h4' className='text-center text-light'>
            Our process is simple...
          </Typography>
        </Stack>
        <Toolbar />

        <Stack spacing={10}>
          <Grid container spacing={1}>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <img
                src={"/pic-1.png"}
                style={{
                  width: '60%',
                  display: "flex",
                  marginLeft: "auto",
                  marginRight: "auto"
                }}
              />
            </Grid>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <Stack sx={{ height: '100%' }}
                justifyContent={"center"}
              >
                <Typography variant='h4' className='text-golden text-center'>
                  Meta Ad Campaign
                </Typography><br />
                <Typography variant='h6'>
                  We&#39;ll create, manage and optimise a highly effective ad campaign to drive qualified leads to your customised landing page. We&#39;ll use precise targeting options to find your ideal prospects and make them want to click your ad.
                </Typography>
              </Stack>
            </Grid>
          </Grid>

          {
            isMobile ?
              <Grid container spacing={1}>
                <Grid item xs={12} sm={12} md={6} lg={6}>
                  <img
                    src={"/pic-2.png"}
                    style={{
                      width: '60%',
                      display: "flex",
                      marginLeft: "auto",
                      marginRight: "auto"
                    }}
                  />
                </Grid>
                <Grid item xs={12} sm={12} md={6} lg={6}>
                  <Stack sx={{ height: '100%' }}
                    justifyContent={"center"}
                  >
                    <Typography variant='h4' className='text-golden text-center'>
                      Landing Page
                    </Typography><br />
                    <Typography variant='h6'>
                      We&#39;ll design and build a landing page explicitly engineered for conversions. We&#39;ll align the landing page&#39;s intentions with the ad&#39;s messaging to ensure the prospect flows effortlessly through your sales funnel.
                    </Typography>
                  </Stack>
                </Grid>
              </Grid>
              :
              <Grid container spacing={1}>
                <Grid item xs={12} sm={12} md={6} lg={6}>
                  <Stack sx={{ height: '100%' }}
                    justifyContent={"center"}
                  >
                    <Typography variant='h4' className='text-golden text-center'>
                      Landing Page
                    </Typography><br />
                    <Typography variant='h6'>
                      We&#39;ll design and build a landing page explicitly engineered for conversions. We&#39;ll align the landing page&#39;s intentions with the ad&#39;s messaging to ensure the prospect flows effortlessly through your sales funnel.
                    </Typography>
                  </Stack>
                </Grid>
                <Grid item xs={12} sm={12} md={6} lg={6}>
                  <img
                    src={"/pic-2.png"}
                    style={{
                      width: '60%',
                      display: "flex",
                      marginLeft: "auto",
                      marginRight: "auto"
                    }}
                  />
                </Grid>
              </Grid>
          }

          <Grid container spacing={1}>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <img
                src={"/pic-3.png"}
                style={{
                  width: '60%',
                  display: "flex",
                  marginLeft: "auto",
                  marginRight: "auto"
                }}
              />
            </Grid>
            <Grid item xs={12} sm={12} md={6} lg={6}>
              <Stack sx={{ height: '100%' }}
                justifyContent={"center"}
              >
                <Typography variant='h4' className='text-golden text-center'>
                  Booking System
                </Typography><br />
                <Typography variant='h6'>
                  We&#39;ll create an automated booking system for your business.<br /><br />
                  A seamless process that allows your prospects to select their own call/appointment time.<br /><br />
                  If you&#39;re an E-commerce brand, we&#39;ll install a product page for prospects to buy from you instantly.
                </Typography>
              </Stack>
            </Grid>
          </Grid>
        </Stack>
      </Container>

      <Toolbar />
      <Footer />
    </>
  )
}
